# Uncomment the next line to define a global platform for your project
# platform :ios, '15.0'

target 'MVP-UI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVP-UI
  
use_frameworks!
pod 'KeychainSwift'
pod 'SwiftGen','~> 6.0'
pod 'XcodeGen', :git => 'https://github.com/yonaskolb/XcodeGen'



platform :ios, '15.0'

end
